'use client';
import {useState} from 'react';
import type {Research} from '@/lib/research';
import {ExplanationText} from './update-explanation';
const time=(s:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Stockholm',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZoneName:'short'}).format(new Date(s));
export function AnalysisPanel({report,fresh}:{report:Research,fresh:boolean}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('all');const a=report.analysis;if(!a)return <p>The analysis will appear when a report is available.</p>;
 const reviewed=a.incidents.filter(i=>i.review==='reviewed'),cutoff=Date.parse(report.checkedAt)-86400000;
 const recent=reviewed.filter(i=>Date.parse(i.reportedAt)>cutoff&&Date.parse(i.reportedAt)<=Date.parse(report.checkedAt)).length;
 const visible=a.incidents.filter(i=>(category==='all'||i.category===category)&&`${i.id} ${i.title} ${i.category} ${i.environment} ${i.cluster}`.toLowerCase().includes(query.toLowerCase()));
 const link=(id:string)=>report.sources.find(s=>s.id===id);
 return <>
 <div className="forecast-heading"><h2>The reset outlook</h2><span className="fine">Looking ahead to the next extra reset</span></div>
 <section className="research-brief">{a.review?<><strong>{a.review.status==='complete'?'Assessment completed':'Assessment incomplete'} · {time(a.review.at)}</strong><details><summary>Evidence considered in this assessment</summary><p>{a.review.reason}</p><ul>{a.review.considered.map(t=><li key={t}>{t}</li>)}</ul></details></>:<p className="fine">No completed full assessment is recorded in this report. The last assessment date is shown below.</p>}</section>
 <section className="outlook-grid">{a.outlooks.filter(o=>o.kind==='any').map(o=>{const position=['LOW','ELEVATED','HIGH','VERY HIGH'].indexOf(o.level);const step=o.position?['lower','middle','upper'].indexOf(o.position)+1:0;return <article className={'outlook-card '+o.kind} key={o.kind}><div className="eyebrow">RESET OUTLOOK</div><p>Signals of the next extra reset.</p><h3>{o.level}{o.position&&<small> · {o.position}</small>}</h3><div className="level-meter" role="img" aria-label={`${o.level}${o.position?`, ${o.position} part`:`, within-level position not yet assessed`} on the low to very high watch scale`}>{['LOW','ELEVATED','HIGH','VERY HIGH'].map((l,i)=><span key={l} className={i<position?'lit':''}><i>{[1,2,3].map(n=><b key={n} className={i<position||(i===position&&n<=step)?'filled':i===position&&!step?'unrated':''}/>)}</i>{l.replace('VERY HIGH','V. HIGH')}</span>)}</div><p className="fine">{o.position?'Three steps per level. Not measured odds.':'Within-level position not yet assessed.'}</p><p className="confidence">Confidence: {o.confidence.toUpperCase()}</p>{o.level==='VERY HIGH'&&<p className="fine">VERY HIGH is a forecast, not confirmation that a reset has arrived or will reach every account.</p>}<p className="fine">{o.trend} · {o.provenance==='imported'?'From earlier research':'Reviewed here'} · {time(o.asOf)}</p>{!fresh&&<p className="notice">Saved outlook · a fresh check is needed</p>}<details><summary>Why this outlook?</summary><p>{o.reason}</p>{o.positionReason&&<p><strong>Position within this level:</strong> {o.positionReason}</p>}<h4>Supporting signals</h4><ul>{o.support.map(t=><li key={t}>{t}</li>)}</ul><h4>Reasons for caution</h4><ul>{o.against.map(t=><li key={t}>{t}</li>)}</ul><h4>What would change the outlook?</h4><p>{o.missing}</p><div className="source-links">{o.sourceIds.map(id=>{const s=link(id);return s?<a href={s.url} key={id} target="_blank" rel="noreferrer">{s.title} ↗</a>:null})}</div></details></article>})}</section>
 <aside className="disclaimer"><div><strong>Guesswork with a little statistics.</strong> These are guesses, not promises. This site is not affiliated with OpenAI or Tibo Sottiaux.</div></aside>
 <section className="research-brief"><div className="eyebrow">COUNTS WITH CONTEXT</div><h2>Usage reports</h2><div className="metric-grid"><div><strong>{a.importedLedger.total}</strong><span>Reports in earlier research</span></div><div><strong>{reviewed.length}</strong><span>Reports reviewed here</span></div><div><strong>{new Set(reviewed.map(i=>i.reporter)).size}</strong><span>Authors of reviewed reports</span></div><div><strong>{recent}</strong><span>Reviewed reports from the past 24 hours</span></div></div><p className="fine">As of {time(report.checkedAt)}. Reviewed means we read the report, not that we proved the bug. These counts overlap.</p><details><summary>Count details and earlier totals</summary><p>{a.importedLedger.note}</p><div className="analysis-columns"><div>{a.importedLedger.categories.map(c=><div className="stat-row" key={c.name}><span>{c.name}</span><strong>{c.count}</strong></div>)}<p className="fine">Also reported: {a.importedLedger.staffFixes} STAFF mechanisms/fixes; {a.importedLedger.officialIncidents} OFFICIAL usage/accounting incidents. These are imported totals, not individually reconstructed counts.</p></div><div className="ledger-chart" role="img" aria-label="Imported cumulative report totals over time">{a.importedLedger.snapshots.map((s,i)=><div key={s.at}><span>{time(s.at)}</span><meter min={0} max={Math.max(...a.importedLedger.snapshots.map(x=>x.total))} value={s.total}/><strong>{s.total}</strong><small>{i?`+${s.total-a.importedLedger.snapshots[i-1].total}`:'baseline'}</small></div>)}<p className="fine">Cumulative totals naturally rise with observation time. This chart is not a bug-incidence rate or a forecast.</p></div></div></details></section>
 <section className="research-brief"><div className="eyebrow">A SMALL HISTORICAL SAMPLE</div><h2>Past gaps between resets</h2><p>Past resets offer context, not a reliable countdown.</p><details><summary>See the historical comparison</summary><p>At the imported checkpoint on {time(a.history.asOf)}, the prior analysis reported <strong>{a.history.ageDays} days</strong> since its automatic-reset reference. Only <strong>{a.history.remainingIntervals.length}</strong> longer intervals remained comparable.</p><div className="metric-grid">{a.history.comparisons.map(c=><div key={c.hours}><strong>{c.hits}/{c.sample}</strong><span>Ended within the following {c.hours===168?'7 days':`${c.hours} hours`}</span></div>)}</div><p>{a.history.note}</p><p className="fine">Retained interval lengths: approximately {a.history.remainingIntervals.join(' and ')} days. This is a dated imported comparison, not a rolling calculation or a probability forecast.</p></details></section>
 <section className="research-brief" id="incidents"><div className="eyebrow">EXPLORE THE EVIDENCE</div><h2>Bug reports</h2><details><summary>Browse reports and evidence</summary><div className="notebook-filters"><label>Search reports<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Issue number, platform or keyword"/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{[...new Set(a.incidents.map(i=>i.category))].map(c=><option key={c}>{c}</option>)}</select></label></div><p className="fine">{visible.length} matching records · thematic clusters group related symptoms, not proven common root causes.</p><div className="incident-grid">{visible.map(i=>{const s=link(i.sourceId);return <article key={i.id}><span className="evidence">COMMUNITY · {i.review}</span><h3><a href={s?.url} target="_blank" rel="noreferrer">#{i.id} · {i.title} ↗</a></h3><p className="fine">{i.category} · {i.environment}</p><p>{i.evidence}</p><details><summary>Evidence and limits</summary><p><strong>Status:</strong> {i.status}</p><p><strong>Cluster:</strong> {i.cluster}</p><p><strong>Limitations:</strong> {i.limitation}</p><p className="fine">Reported {time(i.reportedAt)} · checked {time(i.checkedAt)}. No independent reproduction performed here.</p></details></article>})}</div>{!visible.length&&<p className="empty">No matching reports. Try a different category or search.</p>}</details></section>
 <section className="research-brief" id="updates"><div className="eyebrow">THE CHANGE LOG</div><h2>What changed?</h2><p className="fine">Latest 30 changes, recorded as assessed at the time. The current outlook is above. <a href="/history">Browse earlier reports</a> for retained history.</p>{[...a.changes].sort((a,b)=>Date.parse(b.at)-Date.parse(a.at)).map((c,i)=><article className="change-entry" key={c.at+c.title}><h3>{c.title}</h3><p className="fine">{i===0?'Latest change · ':''}{time(c.at)}</p><details open={i===0}><summary>Why this update?</summary><ExplanationText text={c.detail}/></details></article>)}</section>
 </>;
}
