'use client';
import {useEffect,useState} from 'react';
import type {MonitorRun} from '@/lib/monitor';
const date=(t:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Stockholm',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZoneName:'short'}).format(new Date(t));
type View={state:string;latest:MonitorRun|null;lastSuccess:MonitorRun|null;nextCheck:string;runs:MonitorRun[]};
export function MonitorPanel({onReportPublished}:{onReportPublished:(id:string)=>void}){const [data,setData]=useState<View|null>(null),[error,setError]=useState(false);
 useEffect(()=>{let active=true;const refresh=async()=>{try{const r=await fetch('/api/watchdog/status',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();if(active){setData(d as View);setError(false);if(d.lastSuccess?.reportId)onReportPublished(d.lastSuccess.reportId)}}catch{if(active)setError(true)}};refresh();const timer=setInterval(refresh,60000);return()=>{active=false;clearInterval(timer)}},[onReportPublished]);
 const labels:Record<string,string>={running:'Research in progress',published:'Report published',unchanged:'Checked · no new findings',failed:'Last check failed',missed:'Scheduled check overdue',interrupted:'Research may have been interrupted',unknown:'No check recorded yet',unavailable:'Check status unavailable'};
 return <section className="research-brief" aria-label="Monitoring health"><div className="eyebrow">IS THE WATCHDOG WATCHING?</div><h2>{error?'Check status unavailable':data?labels[data.state]:'Loading check status…'}</h2><p>Last checked: {data?.lastSuccess?date(data.lastSuccess.updatedAt):'Not recorded'}. Next scheduled check: {data?.nextCheck?date(data.nextCheck):'Unavailable'}.</p><p className="fine">A check runs every hour, day and night. The report changes only when there is something new to share.</p><details><summary>Recent checks and details</summary><p className="fine">Checks run in Codex on DEV3. The server, app and network must be available. Closing the remote desktop connection does not stop the schedule. Times use Europe/Stockholm. A check is marked late after 45 minutes.</p>{data?.runs.map(r=><article key={r.runId}><strong>{date(r.startedAt)} · {r.mode} · {labels[r.status]}</strong><p>{r.detail}</p>{r.channels.map(c=><p className="fine" key={c.name}>{c.name}: {c.status} — {c.detail}</p>)}</article>)}</details></section>;
}
