'use client';
import {useEffect,useState} from 'react';
import type {WatchdogUsage} from '@/lib/monitor';
const number=(value:number)=>new Intl.NumberFormat('en-GB').format(value);
const date=(value:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Stockholm',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'short'}).format(new Date(value));
export function UsagePanel(){
 const [usage,setUsage]=useState<WatchdogUsage|null>(null),[state,setState]=useState('loading');
 useEffect(()=>{let active=true;const refresh=async()=>{try{const response=await fetch('/api/watchdog/status',{cache:'no-store'});if(!response.ok)throw Error();const data=await response.json() as {usage:WatchdogUsage|null};if(active){setUsage(data.usage);setState(data.usage?'ready':'unavailable')}}catch{if(active)setState('unavailable')}};void refresh();const timer=setInterval(refresh,60000);return()=>{active=false;clearInterval(timer)}},[]);
 return <section className="research-brief" id="operating-usage" aria-label="Watchdog operating usage"><div className="eyebrow">OPERATING USAGE · EXPERIMENT</div><h2>What it takes to keep watch</h2>{state==='loading'?<p>Loading usage measurements…</p>:state!=='ready'||!usage?<p>Usage measurements are currently unavailable.</p>:<><div className="usage-totals"><div><strong>{number(usage.measuredRuns)}</strong><span>Measured checks</span></div><div><strong>{number(usage.totalTokens)}</strong><span>Total tokens</span></div></div><p className="fine">Measured from {date(usage.since)}. Completed checks included through {date(usage.through)}.</p>{usage.unmeasuredRuns>0&&<p>{number(usage.unmeasuredRuns)} completed checks could not be measured and are excluded from these totals.</p>}<details><summary>What these numbers include</summary><p>Completed scheduled Watchdog runs only, including research, analysis, publication and verification. Development, manual conversations and separate upstream research tasks are excluded. The current run is added after it finishes, usually when the next check starts.</p><p>Input: {number(usage.inputTokens)} tokens, including {number(usage.cachedInputTokens)} cached tokens. Output: {number(usage.outputTokens)} tokens. Cached input is already included in the total; it is not added twice.</p><p>These are recorded token counts, not a monetary cost or a percentage of the weekly allowance. Reused context can be counted again in later requests.</p><p className="fine">Measurement updated {date(usage.updatedAt)}.</p></details></>}</section>;
}
