import assert from 'node:assert/strict';
import {runSchema,monitoringState,scheduleWindow} from '../lib/monitor.ts';
const now=Date.parse('2026-09-20T07:50:00Z');
const base={runId:'check-test',startedAt:'2026-09-20T07:00:00Z',updatedAt:'2026-09-20T07:01:00Z',mode:'light',status:'running',detail:'Checking',channels:[]};
assert.equal(monitoringState([base],now).state,'interrupted');
assert.equal(monitoringState([],now).state,'missed');
assert.equal(monitoringState([{...base,status:'unchanged'}],now).state,'unchanged');
assert.equal(monitoringState([{...base,status:'failed'}],now).lastSuccess,null);
assert.equal(monitoringState([{...base,status:'published'}],now).state,'published');
assert.equal(runSchema.safeParse({...base,startedAt:'2026-09-19T07:00:00Z',updatedAt:'2026-09-19T07:01:00Z',status:'published'}).success,false);
assert.equal(runSchema.safeParse({...base,startedAt:'2026-09-19T07:00:00Z',updatedAt:'2026-09-19T07:01:00Z',status:'published',reportId:'report-test'}).success,true);
for(const d of ['2026-10-25T01:50:00Z','2026-03-29T01:50:00Z']){const n=Date.parse(d);const w=scheduleWindow(n);assert(w.previous<=n&&w.next>n);}
assert.equal(new Date(scheduleWindow(Date.parse('2026-09-20T08:10:00Z')).next).toISOString(),'2026-09-20T09:00:00.000Z');
assert.equal(monitoringState([{...base,status:'published'}],Date.parse('2026-09-20T08:46:00Z')).state,'missed');
console.log('Passed: missed checks, interrupted runs, failures, completion, publication validation and DST schedule.');
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const code=ts.transpileModule(fs.readFileSync('app/api/watchdog/status/route.ts','utf8').replace(/^import .*;$/gm,''),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const records=new Map();
const DB={prepare(sql){return{bind(...args){return{async first(){const body=records.get(args[0]);return body?{body}:null},async run(){const [key,body]=args;const old=records.get(key);const incoming=JSON.parse(body);if(!old||JSON.parse(old).status==='running'&&JSON.parse(old).startedAt===incoming.startedAt&&Date.parse(incoming.updatedAt)>Date.parse(JSON.parse(old).updatedAt))records.set(key,body)}}},async all(){return {results:[...records.entries()].filter(([k])=>k.startsWith('monitor-run-')).map(([,body])=>({body}))}}}}};
const ctx={exports:{},env:{DB,WATCHDOG_INGEST_TOKEN:'test-only'},runSchema,monitoringState,Response,Request,crypto,TextEncoder,TextDecoder,Uint8Array,Date};vm.runInNewContext(code,ctx);
const r={...base,startedAt:'2026-09-19T07:00:00Z',updatedAt:'2026-09-19T07:00:00Z'};
const post=(body,auth='Bearer test-only')=>ctx.exports.POST(new Request('http://test/api/watchdog/status',{method:'POST',headers:{Authorization:auth},body:JSON.stringify(body)}));
assert.equal((await post(r,'wrong')).status,401);
assert.equal((await post({...r,privateAccount:'secret'})).status,400);
assert.equal((await post(r)).status,200);
assert.equal((await post(r)).status,200);
const done={...r,updatedAt:'2026-09-19T07:01:00Z',status:'published',reportId:'saved-report'};
assert.equal((await post(done)).status,409,'Cannot claim publication without report archive');
records.set('research-v2-run-saved-report','{}');assert.equal((await post(done)).status,200);
assert.equal((await post({...r,updatedAt:'2026-09-19T07:02:00Z'})).status,409,'Cannot reopen terminal run');
assert.equal((await (await ctx.exports.GET()).json()).lastSuccess.reportId,'saved-report');
console.log('Passed: monitoring authentication, strict fields, idempotency, publication prerequisite and terminal-state protection.');
